# Generated by Django 4.0.2 on 2022-02-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('adresses', models.TextField()),
            ],
        ),
    ]
